### ISSUE TITLE
[TODO] 4th Week of July, 2022

### ISSUE THREAD

**Issue by junsu0925** [junsu0925/FFR-Array#1]
- [x] FFR Array (two) - Admittance & TVR
- [x] FFR Array (two) - g/a parameter study

- [x] FFR Array (three) - Admittance & TVR
- [x] FFR Array (three) - g/a parameter study

- [x] FFR Array (four) - Admittance & TVR
